spring.application.name=gateway-pagamento

# Database (commented for Testcontainers in tests)
# spring.datasource.url=jdbc:postgresql://localhost:5432/gateway_pagamento
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
